http.enabled: true

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true

metricbeat.autodiscover:
  providers:
    - type: jolokia
      templates:
        - condition:
            contains:
              jolokia.agent.version: "1.6.2"
          config:
            - module: "jolokia"
              metricsets: ["jmx"]
              hosts: ["${data.jolokia.url}"]
              namespace: "jvm"
              jmx.mappings:
                - mbean: 'java.lang:type=OperatingSystem'
                  attributes:
                    - attr: "ProcessCpuLoad"
                      field: "processCpuLoad"
                      type: float
                    - attr: "SystemCpuLoad"
                      field: "systemCpuLoad"
                      type: float
                - mbean: 'java.lang:type=Runtime'
                  attributes:
                    - attr: Uptime
                      field: uptime
                - mbean: "java.lang:type=Memory"
                  attributes:
                    - attr: "HeapMemoryUsage"
                      field: "memory.heap"
                    - attr: "NonHeapMemoryUsage"
                      field: "memory.nonheap"
                - mbean: "java.lang:type=Threading"
                  attributes:
                    - attr: "ThreadCount"
                      field: "thread.count"
                - mbean: "kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions"
                  attributes:
                    - attr: "Value"
                      field: "kafka.partitions.underReplicatedPartitionsCount"
                - mbean: "kafka.controller:name=OfflinePartitionsCount,type=KafkaController"
                  attributes:
                    - attr: "Value"
                      field: "kafka.partitions.offlinePartitionsCount"

#processors:
#  - add_cloud_metadata: ~

setup.dashboards.enabled: true

setup.kibana.host: '${KIBANA_HOST:kibana:5601}'

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
